### ISSUE TITLE
Loading to numpy array is slow

### ISSUE THREAD

**Issue by darius** [sorki/python-mnist#25]
If I load the full data with result_type of 'numpy', it takes over 4 seconds. I can get it down to around half a second with the following approach, which I'm not going to make into a pull request because it would require refactoring the surrounding class. Just thinking it'd be nice to share what I found.

In mnist/loader.py, the `load` method, instead of `images`, return `np.array(image_data).reshape((size, rows*cols))` (and don't create the `images` list). In other words, instead of creating thousands of small numpy arrays, create just one array with one more dimension, directly on the byte array read from the file.

**Comment by darius** [comment]
(Actually more like 0.2 second real time after the change; I was mindlessly reporting the system time from the `time` command.)

**Comment by sorki** [comment]
:smiley: 

The lib was never supposed to be fast since the time loading the datasets is typically not the most significant part of the ML process. Originally it was implemented using only plain Python since all the existing `numpy` solutions were out of date. Now the `numpy` backend is there again but strictly optional.
